export * as trendings from './rest/trendings'
export * as readme from './rest/readme'
export * as starred from './rest/starred'
export * as user from './rest/user'
export * as issues from './rest/issues'
